version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: postgres 
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 10

  loader:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    command: python loader/load_data.py

  visualizer:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    command: python visualizer/visualize.py
    volumes:
      - ./visualizer/libs:/app/visualizer/libs
      - ./visualizer/quark.html:/app/visualizer/quark.html

volumes:
  pgdata:
